language: perl
perl:
  - "5.19"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
env:
  - TEST_LIVE=1 TEST_HOST=localhost TEST_PORT=9200
  - TEST_LIVE=1 TEST_HOST=localhost TEST_PORT=9200 HIJK_XS=1

before_install:
  - curl --silent -L http://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-0.90.7.tar.gz | tar -xz
  - ./elasticsearch-0.90.7/bin/elasticsearch
  - sleep 5
  - yes | perl -MCPAN::FirstTime -e CPAN::FirstTime::init
  - cpanm --notest --verbose Module::Install Module::Install::CPANfile Devel::Cover Devel::Cover::Report::Coveralls
  - (cd Hijk-HTTP-XS && perl Makefile.PL && make)

script:
  PERL5OPT=-MDevel::Cover prove -Ilib -IHijk-HTTP-XS/lib -I Hijk-HTTP-XS/blib/arch/ -I Hijk-HTTP-XS/blib/lib -r t && cover -report coveralls

notifications:
  irc:
    channels:
      - "irc.freenode.org#chupei.pm"
    use_notice: true

